package com.indai.assistant;

import android.content.Context;
import android.content.Intent;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public final class ChatExporter {

    public static String toMarkdown(JSONArray history) {
        StringBuilder sb = new StringBuilder();
        SimpleDateFormat fmt = new SimpleDateFormat("MMM d, yyyy · HH:mm", Locale.getDefault());
        SimpleDateFormat time = new SimpleDateFormat("HH:mm", Locale.getDefault());

        int userCount = 0;
        int aiCount = 0;
        int toolCount = 0;

        // ============ HEADER ============
        sb.append("# 🧠 Ind AI — Conversation\n\n");
        sb.append("> _Exported ").append(fmt.format(new Date())).append("_\n\n");

        // ============ METADATA ============
        sb.append("| | |\n");
        sb.append("|---|---|\n");
        sb.append("| **Source** | Ind AI for Android |\n");
        sb.append("| **Exported** | ").append(fmt.format(new Date())).append(" |\n");
        // Pre-count for stats
        for (int i = 0; i < history.length(); i++) {
            try {
                JSONObject m = history.getJSONObject(i);
                String role = m.optString("role");
                String content = m.optString("content", "");
                if ("user".equals(role)) {
                    if (content.startsWith("TOOL_RESULT:")) toolCount++;
                    else userCount++;
                } else if ("assistant".equals(role)) {
                    aiCount++;
                }
            } catch (Exception ignored) {}
        }
        sb.append("| **Messages** | ").append(userCount + aiCount)
          .append(" (").append(userCount).append(" you · ")
          .append(aiCount).append(" Ind AI");
        if (toolCount > 0) sb.append(" · ").append(toolCount).append(" actions");
        sb.append(") |\n");
        sb.append("\n---\n\n");

        // ============ BODY ============
        for (int i = 0; i < history.length(); i++) {
            try {
                JSONObject m = history.getJSONObject(i);
                String role = m.optString("role");
                if ("system".equals(role)) continue;
                String content = m.optString("content", "");
                if (content.isEmpty()) continue;

                if ("user".equals(role)) {
                    if (content.startsWith("TOOL_RESULT:")) {
                        String action = content.substring(12).trim();
                        sb.append("### ⚡ Action\n\n");
                        sb.append("> ").append(escape(action).replace("\n", "\n> ")).append("\n\n");
                    } else {
                        sb.append("### 🧑 You\n\n");
                        sb.append("> ").append(escape(content).replace("\n", "\n> ")).append("\n\n");
                    }
                } else if ("assistant".equals(role)) {
                    sb.append("### 🤖 Ind AI\n\n");
                    sb.append(content).append("\n\n");
                }
            } catch (Exception ignored) {}
        }

        // ============ FOOTER ============
        sb.append("---\n\n");
        sb.append("<sub>Generated by **Ind AI** · ")
          .append(userCount + aiCount)
          .append(" messages</sub>\n");

        return sb.toString();
    }

    private static String escape(String s) {
        if (s == null) return "";
        // Escape markdown special chars that would break formatting
        return s.replace("|", "\\|");
    }

    public static void share(Context ctx, JSONArray history) {
        String md = toMarkdown(history);
        Intent i = new Intent(Intent.ACTION_SEND);
        i.setType("text/plain");
        i.putExtra(Intent.EXTRA_SUBJECT, "Ind AI conversation");
        i.putExtra(Intent.EXTRA_TEXT, md);
        ctx.startActivity(Intent.createChooser(i, "Export conversation"));
    }

    private ChatExporter() {}
}
